apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: hnortodz0-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-de57320b13.4wjs.p3.openshiftapps.com/rhtap/rhtap-qe:bd3e0164723438a3a3d715a4774cf9238cd525fb@sha256:9f39f830a23a49ca7594eac99e33b8cbd1002a01f047060356f314f1f8c415a3
        name: container-image  
